max_ws_terminals: 10
max_shared_desktop_conn: 4
ws_ping_interval: 20 # seconds
ws_timeout: 1080 # minutes
server_bind_address: 0.0.0.0:8080
debug: false
sf_endpoints: 
  - "3.126.148.157"
  - "217.79.189.141"
  - "23.134.94.196"
  - "82.151.200.71"
  - "136.243.39.18"
  - "144.76.220.20"
sf_ui_origin: http://127.0.0.1:8080
disable_origin_check: true
use_x_forwarded_for_header: false
disable_desktop: false
work_directory: /dev/shm
start_xpra_command: "[[ $(ss -lnt) == *2000* ]] || /sf/bin/startxweb"
start_vnc_command: "[[ $(ss -lnt) == *5900* ]] || /sf/bin/startxvnc"
start_filebrowser_command: "[[ $(ss -lnt) == *2900* ]] || /sf/bin/startfb"
client_inactivity_timeout: 1
vnc_port: 5900
filebrowser_port: 2900
segfault_ssh_username: root
segfault_ssh_password: segfault
segfault_use_ssh_key: false
segfault_ssh_key_path: /tmp/id_rsa
enable_metric_logging: false
elastic_server_host: "sf-stats.segfault.net"
elastic_index_name: "sf-stats"
elastic_username: "elastic"
elastic_password: "elastic"
geo_ip_db_path: "geo.mmdb"
